-- CreateEnum
CREATE TYPE "HistoryType" AS ENUM ('QUESTION_CREATE', 'ANSWER_CREATE', 'COMMENT_CREATE', 'QUESTION_EDIT', 'ANSWER_EDIT', 'COMMENT_EDIT', 'QUESTION_VOTE', 'ANSWER_VOTE', 'COMMENT_VOTE', 'QUESTION_DOWNVOTE', 'ANSWER_DOWNVOTE', 'COMMENT_DOWNVOTE', 'ANSWER_CHOSEN', 'REPORT_CREATE', 'QUESTION_DELETE', 'ANSWER_DELETE', 'COMMENT_DELETE');

-- CreateTable
CREATE TABLE "History" (
    "id" TEXT NOT NULL,
    "type" "HistoryType" NOT NULL,
    "userId" TEXT NOT NULL,
    "contentTitle" TEXT NOT NULL,
    "questionId" TEXT,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "History_pkey" PRIMARY KEY ("id")
);

-- AddForeignKey
ALTER TABLE "History" ADD CONSTRAINT "History_userId_fkey" FOREIGN KEY ("userId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
